aza547/wow-recorder

- src/main/logutils.ts
> correcting issue where wrong result is show for arena matches

- src/main/util.ts
Also removed unused methods that existed in the file.
> Correct https://github.com/aza547/wow-recorder/issues/22

- CHANGELOG.md
- package.json
- release/app/package-lock.json
- src/main/obsRecorder.ts
- src/main/util.ts
- Remove bitrate cap. 
- Fix resolution so not 1920x1080 hardcoded.
- Remove some random packages we don't use. 
- Small tweaks to code style elsewhere.
> Quality improvements

- src/renderer/index.ejs
fixes #55 
resubmitted as I messed up with #56
> set window title to "Warcraft Recorder"

- CHANGELOG.md
- src/renderer/Status.tsx
> Fix EventEmitter leak in Status component

- src/main/constants.ts
- src/main/logutils.ts
- src/main/util.ts
- src/renderer/App.css
- src/renderer/VideoButton.tsx
- src/renderer/rendererutils.ts
Closes #53. As the title says, introduces the saving and display of the difficulty for raids.
There isn't much space left on the VideoButton, but I managed to fit it in.
> Feature: Raid instance difficulty

- CHANGELOG.md
- src/main/main.ts
- src/main/obsAudioDeviceUtils.ts
- src/main/obsRecorder.ts
- src/main/operatingSystems.ts
- src/main/preload.ts
- src/main/recorder.ts
- src/main/util.ts
- src/settings/Settings.tsx
Implement a way to seelct input and output devices for recording via Settings. Fixes #17
> Feature: Select audio device

- CHANGELOG.md
- release/app/package.json
- src/main/main.ts
- src/main/obsRecorder.ts
- src/main/util.ts
- src/renderer/RendererTitleBar.tsx
- src/renderer/index.ejs
Rebase to main instead of merge
> Partial recorder bug

- CHANGELOG.md
- src/main/main.ts
- src/renderer/App.css
- src/renderer/App.tsx
- src/renderer/VersionUpdateWidget.tsx
Addresses #74 
Also cleans up button bar css
> Feature check updates

- CHANGELOG.md
- src/main/main.ts
- src/main/recorder.ts
- src/main/types.ts
- src/main/util.ts
- src/renderer/Layout.tsx
Application is somewhat slow to start up, especially with storage on mechanical drives, if there are many videos.
This change simply makes the loading of videos asynchronous.
> Added async load of videos for responsiveness

- CHANGELOG.md
- release/app/package.json
- src/main/recorder.ts
- src/main/util.ts
> Bug fix 123 & 128

- CHANGELOG.md
- src/main/obsRecorder.ts
- src/main/recorder.ts
> Fix issue 139

- src/main/obsRecorder.ts
- src/main/util.ts
Remove accidental `console.log()`
> Solve mirrored resolutions issue

- README.md
for those who want that option.
> Add non-curseforge addon links

- README.md
- docs/CHANGELOG.md
- src/renderer/Layout.tsx
This makes videos auto play after they're selected, but not on first boot or when changing categories
> Autoplay videos after they are selected

- docs/CHANGELOG.md
- src/settings/VideoSettings.tsx
> fix issue 288 - fps setting bug

- docs/CHANGELOG.md
- release/app/package-lock.json
- src/renderer/App.css
- src/renderer/VideoButton.tsx
* Adds css selector for child divs of .videoButton to show overflowing text as ellipsis.
> 251: Weird cropping of M+ dungeon names

- docs/CHANGELOG.md
- src/main/Recorder.ts
- src/settings/AudioSettings.tsx
> dont allow users to select a million devices

- docs/CHANGELOG.md
- src/settings/AdvancedSettings.tsx
> remove some encoders

- docs/CHANGELOG.md
- package.json
- src/__tests__/activitys/Battleground.test.ts
- src/__tests__/activitys/RaidEncounter.test.ts
- src/__tests__/activitys/SoloShuffle.test.ts
- src/main/main.ts
Time to actually add some UTs. 
I'm expecting this will cover the combatlog parsing primarily, and some other bits. 
Fixes #34
> 34 unit tests

- docs/CHANGELOG.md
- src/main/constants.ts
- src/renderer/App.css
#348 
Updated seek bar CSS height to be taller.
Includes: 
- Seek Bar
- Markers
- Mouse over display
Fix: first boss name of Court of Stars.
> style: Updated Seek Bar

- docs/CHANGELOG.md
- package-lock.json
- package.json
- src/renderer/Layout.tsx
- src/renderer/VideoJS.tsx
J: Backwards 10
K: Play/Pause
L: Forward 10
Closes #334
> Added JKL Hotkeys

- README.md
- docs/CHANGELOG.md
- installer.nsh
- package.json
- release/app/package.json
> installer fix

- src/main/constants.ts
> Support for ultrawide 5k displays

- release/app/package-lock.json
- src/renderer/FlavourSettings.tsx
- src/renderer/RaidEncounterInfo.tsx
- src/renderer/components/Menu/Item.tsx
- src/renderer/components/MultiSelect/MultiSelect.tsx
Fixes the minor UI bugs from [Issue 518](https://github.com/aza547/wow-recorder/issues/518)
> fix: Fix some UI bugs discovered [Issue#518]

- src/main/constants.ts
Fix dawnbreaker and grim batol timers
> Update constants.ts - TWW M+ timers

- src/main/constants.ts
Siege of Boralus timer fix for TWW S1
> Update constants.ts - sob timer TWW S1

- CHANGELOG.md
- src/activitys/RaidEncounter.ts
- src/main/types.ts
- src/main/util.ts
- src/parsing/LogHandler.ts
- src/parsing/RetailLogHandler.ts
- src/renderer/rendererutils.ts
the backend needs some attention before this can go
> add boss percentages

- src/renderer/VideoPlayer.tsx
- src/renderer/components/DrawingOverlay/DrawingOverlay.tsx
I was curious about excalidraw so I tested it. I added it by referring to the documentation on localization and it seems to be normal.
Excalidraw [Utils](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/) [Props](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/utils)
> DrawingOverlay local

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/main/Manager.ts
- src/main/Recorder.ts
- src/main/util.ts
- src/parsing/LogHandler.ts
- src/renderer/App.tsx
- src/renderer/VideoPlayer.tsx
- src/utils/Poller.ts
[Forks OSN](https://github.com/aza547/obs-studio-node-wcr) and adds force stop function. 
- That gives is a route to recovery without restarting OBS.
- Lets us gracefully sleep without restarting OBS.
> Expose and use obs_output_force_stop

- CHANGELOG.md
- release/app/package.json
- src/__tests__/activitys/ChallengeModeDungeon.test.ts
- src/activitys/ChallengeModeDungeon.ts
- src/main/constants.ts
- src/parsing/ClassicLogHandler.ts
- src/parsing/LogHandler.ts
- src/parsing/RetailLogHandler.ts
- src/renderer/components/Tables/Cells.tsx
- src/renderer/rendererutils.ts
- tests/src/classic/mop_challenge_mode.py
- tests/src/test.py
Still needs:
- Logic in ChallengeModeDungeon for handling if Flavor === Classic
- Some unit tests for that? Maybe
- A test log checked in.
- A test added to the test.py infrastructure.
> wip: MOP Challenge Modes
