aza547/wow-recorder

package-lock.json
package.json
src/renderer/Layout.tsx

'@mui/styles' is deprecated, tss-react is recommended to replace it.
I couldn't see any issues in some limited testing, all the UI seemed functional and looking the same.
fixes #79

replace '@mui/styles' with 'tss-react/mui'

---

src/renderer/Layout.tsx

Fixes #86.
The listener on `ipc.on('refreshState')` was attached on every re-render, and this commit fixes that by making sure the listener only attached once per component load/unload.
This caused memory leaks as logged in the console:
```
(node:14384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
11 refreshState listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```
`React.useEffect()` triggers on every state update, but when given an empty array as its 2nd argument, it changes that to only trigger on component load/unload.
The scenario is described in the React documentation here:
https://www.robinwieruch.de/react-function-component/#react-function-component-lifecycle
under section "React Function Component: Lifecycle".

Fix memory leak from EventEmitter

---

src/settings/Settings.tsx

In the Settings window, if "**Run on Startup?**" is repeatedly clicked or if some other action causes redraw of the component, it would attach an event listener for `'settingsWindow'` on every redraw.
This caused a potential memory leak which this commit fixes.
Related to issue #86

Fix EventEmitter memory leak in settings

---

CHANGELOG.md
src/main/util.ts

If a video is open in another application, like VLC, and the application is closed - or if you attempt to delete that video - the app would throw an exception that we didn't catch.
This commit changes that so that we'll catch the error and log it to the console.
Fixes #78

Fixes cleanup errors if files are locked

---

CHANGELOG.md
src/main/logutils.ts

Split log lines intelligently with respect to quotes, lists, tuples and what have we such that we can better use the data contained within the log lines.
`splitLogLine`  has a `maxSplits` argument that, when given, will limit the maximum number of parsed arguments returned. Technically, it's advisable to only parse up to as many arguments as needed, but that isn't done yet as that'd probably be a pre-emptive overoptimization.
The method now returns an instance of the new class `LogLine`, which contains both the timestamp and the line arguments. At the same time, all `handle*Line` methods have been updated to accept an argument of `LogLine` instead of a string.
`getCombatLogDate` has been moved to `LogLine` and simply called `date()`, all occurances of the former has been replaced by the …

Replace `string.split()` with `splitLogLine()`

---

CHANGELOG.md
package-lock.json
package.json
src/main/main.ts
src/main/recorder.ts
src/main/util.ts

- Replace `glob` with `glob-promise` to be able to perform async globbing.
- Import `fs-promise` as `fs`and rename `fs` to `fscb` as `fs-promise` cannot be renamed on its import, as far as I know.
- Create async `getSortedVideos()` to find and return all video files sorted by modification time. This method will read all metadata for every video which by itself is a performance penalty, but considering modern hardware it should be neglible and not noticable.
- Remove `isVideoProtected()` as `getSortedVideos()` replace this.
- Create async `writeMetadataFile()` to reduce duplicate code.
- Refactor `deleteOldestVideo()` and `getNewestVideo()` to be async.
- Create `saveMetadataForVideo()`.
- Refactor `toggleVideoProtected()` to use `getMetadataForVideo()`/`saveMetadataForVideo()`.
This fixes …

Fix sizeMonitor() blocking the thread

---

src/main/main.ts
src/main/recorder.ts
src/main/types.ts
src/renderer/Status.tsx

This is to make it more easier to identify the status values in the code and allow stronger typing on the values.
- Create an enum for the application status values in a new module, `main/types`.
- Replace `if..else` with an object of messages mapped to the new `AppStatus` enums.

 Cleanup application status values and logic

---

src/main/recorder.ts

There was a mixup of `AppStatus` being moved from `main/main.ts` to `main/types.ts` and a reference wasn't updated to reflect that.

Fix: Wrong/missing import for AppStatus

---

src/main/logutils.ts
src/main/types.ts

- Add `enum UnitFlag` to types for easier identification of the various flags that a unit can have.
- Add `isUnitPlayer()` to easier identify a player controlled unit.
- Refactor `isUnitSelf()` to make use of `isUnitPlayer()` and `UnitFlags`.
To prove that nothing has change logically, the old `isUnitSelf()` method checked the flags against the hexadecimal value 0x511 which consists of the flags:
```typescript
UnitFlags.AFFILIATION_MINE = 1
UnitFlags.REACTION_FRIENDLY = 16
UnitFlags.CONTROL_PLAYER = 256
UnitFlags.TYPE_PLAYER = 1024
```
1297 decimal, 0x511 hex.

Cleanup the isUnitSelf() method

---

src/main/logutils.ts

Combat log line:
```log
9/15 20:46:15.096  ZONE_CHANGE,1195,"Iron Docks",23
```
Code:
```typescript
console.log(splitLogLine('9/15 20:46:15.096  ZONE_CHANGE,1195,"Iron Docks",23', 1));
```
Before change:
```js
LogLine {
original: 'ZONE_CHANGE,1195,"Iron Docks",23',
timestamp: '9/15 20:46:15.096',
args: [
'ZONE_CHANGE',
'ZONE_CHANGE,1195',
'ZONE_CHANGE,1195,Iron Docks',
'ZONE_CHANGE,1195,Iron Docks,23'
]
}
```
After change:
```js
LogLine {
original: 'ZONE_CHANGE,1195,"Iron Docks",23',
timestamp: '9/15 20:46:15.096',
args: [ 'ZONE_CHANGE' ]
}
```

Fix: splitLogLine() max splits error and LogLine.date() off-by-one

---

src/main/constants.ts
src/main/logutils.ts
src/main/util.ts
src/renderer/VideoButton.tsx
src/renderer/rendererutils.ts

As the title states. A simple refactor to eliminate literal strings from comparisons and assignments.

Refactor 'categories' to be an enum type

---

src/main/util.ts

Ensure that metadata JSON is written to disk in UTF-8 encoding to support e.g. Russian character names. This relates to the new `playerDeath` metadata array which can look garbled when Russian character names appear in it.

Write metadata with UTF-8 encoding

---

src/renderer/App.css
src/renderer/VideoButton.tsx

- Remove "zone" text and include only the map name, which is the only important part for a dungeon.
- Add Keystone level at the top where raids have their difficulty letter displayed and make it LEGENDARY colored.
- Make dungeon map name centered vertically and horizontally to it looks nice

Make <VideoButton/> for M+ look nice

---

src/main/main.ts
src/main/preload.ts
src/main/types.ts
src/renderer/Layout.tsx

Closes #99.
When a video is muted or the volume changed, that setting would only persist within the selected video category (e.g. 3v3) and if a different category was selected, the settings would reset which was undesirable.
This has been changed such that the settings are _global_ across the app regardless of category and video selection.
- New type `VideoPlayerSettings` which contains the muted/volume state values that we want to preserve.
- New IPC channel `videoPlayerSettings` with two main functions as `args[0]`:
`get`: retrieve the stored settings
`set`: store the settings given in `args[1]`
- IPC listener to get/set video player settings.
- New function `handleVideoPlayerVolumeChange()` which handles saving the state of the muted/volume when it changes and sets the values in the …

Make video player settings global

---

src/main/main.ts

Fixes issue #119 which describes a problem in which an invalid configuration, as how the initial state of the app is for new users, will crash when one attempts to open the Settings window.
This is due to OBS not yet being initialized but attempted to be used to retrieve available input/output audio devices.
The fix is to simply return an empty array for these device arrays and let the config only show "All" and "None" until OBS has been initialized.

Fix crashing with invalid configuration

---

package-lock.json
package.json
src/main/util.ts

Also print out size of maximum and the total video library size using `byte-size` package, that will automatically format it with appropriate unit suffixes and such.
Remove the `Promise.resolve()` from `runSizeMonitor()` as it isn't needed for a return type of `Promise<void>`.
Add `path.resolve()` to normalize all path separators for the OS so logging doesn't have `C:\..\` and `C:/../` which can look confusing.

Add more logging to size monitor

---

CHANGELOG.md
src/main/logutils.ts

In the case of raids, it's not unusual for a player to die _before_ an encounter starts for various reasons (e.g. trash) but as we don't have a `videoStartDate` before the recording/encounter starts, this caused the application to crash due to trying to access `videStartDate.getTime()`.
This fix simply guards `handleUnitDiedLine()` in such a way where if we are not recording or if we don't have a valid `videoStartdate`, we'll ignore `UNIT_DIED`.
Fixes issue #134

Fix UNIT_DIED handling before recording starts

---

package.json

During development, hot-reloading can create annoying situations when Git modifies files in `.git` as well as when test scripts or files are updated in `resources/`.
These paths have been added to ElectroMon's patterns with a negation to avoid them triggering hot-reloading.

Avoid hot-reloading during development for .git

---

CHANGELOG.md
src/renderer/Layout.tsx
src/renderer/preload.d.ts

Whenever a new category is selected, it'll be saved to the `selected-category` persistent setting and restored when the app restarts.

Remember the selected category across restarts

---

CHANGELOG.md
src/main/constants.ts
src/main/helpers.ts
src/main/recorder.ts
src/main/types.ts
src/main/util.ts
src/renderer/VideoButton.tsx
src/renderer/rendererutils.ts

This adds an easy and scalable way to find a raid name from an encounter ID; `raidInstances` is an array of raids with zone ID, name, and a list of encounters (by encounter ID).
Hashmap `instanceEncountersById` has been added to have a single point of truth regarding encounter IDs to encounter name for all instances that support this (dungeons, raids).
A new file has been added, `helpers.ts`, which should be kept FREE from any filesystem related modules (as these cannot be imported in the renderer process) and some of the helper functions from both `utils.ts` as well as `renderutils.ts` has been moved here, as they were needed in multiple places.
This file utilizes the format of `export const methodName = () => {};` as it avoids having a long list of exported names at the bottom, and …

Name video files more sensibly

---

src/main/obsRecorder.ts

Given the following:
```js
const physicalWidth = 2560;
const physicalHeight = 1440;
```
And the following code:
```js
const outputWidth = physicalWidth;
const outputHeight = physicalHeight;
const videoScaleFactor = physicalWidth / outputWidth;
sceneItem.scale = { x: 1.0 / videoScaleFactor, y: 1.0 / videoScaleFactor };
```
Let's replace the values of these variables and resolve the calculations:
```js
const outputWidth = 2560;
const outputHeight = 1440;
const videoScaleFactor = 2560 / 2560;
sceneItem.scale = { x: 1.0 / 1, y: 1.0 / 1 };
```
Which makes the removed lines completely pointless.
I am unsure whether the following is even needed after removing this, but leaving it in due to the uncertainty:
```js
sceneItem.scale = { x: 1.0, y: 1.0 };
```

Remove pointless code

---

src/main/obsRecorder.ts
src/main/util.ts

The previous method of checking if a number was close to another number was a bit fuzzy.
This change introduces a new method `getClosestResolution()` which, given an array of available resolutions from OBS and a target resolution to match, will return the one that _closest_ match.
This means we'll _never_ crash due to not being able to find a resolution that matches, as it'll always return the one that closest match.
`isNumberClose()` has been removed due to this.
To prove that this works as good, and better, than the method with `isNumberClose()` (which was prone to errors when scaling goes up), here's an example from issue #123 where the reporter has a 4K monitor with 3840x2160 resolution and 175% scaling in Windows:
I added some extra resolutions to the array of available resolutions …

Make finding resolutions more robust

---

CHANGELOG.md
src/main/main.ts
src/main/obsRecorder.ts
src/main/types.ts
src/main/util.ts
src/settings/Settings.tsx

`getAttribute()` returns `null`, specifically, when an element does not have the given attribute but the logic wasa simply testing the `value` as being 'truthy', which meant that `0` or even an empty string wouldn't be saved.
Monitor indexes are zero based and therefore we couldn't save monitor index `0`. We can now!
Created a new method for retrieving the available monitors from Electron (which is the same as being provided from OBS, but with types!) and creates a new array for the frontend to display to make the selection easier.
Replace the input text field with a dropdown selector box that displays the available monitors in a slightly better way which should hopefully make it easier to distinguish the individual monitors of ones system.
Example:
Closes #81

Feature: Better monitor selector

---

src/main/combatLogParser.ts

In an attempt to make TypeScript happy, all `continue` statements in the block of `switch (char) {` were changed to `break` with a single continue at the end.
This had the unfortunate consequence that it didn't parse anything because it never added non-special characters to the `value` variable.
This fixes that.

Fix breaking change to `splitLogLine()`

---

src/main/combatLogParser.ts
src/main/logutils.ts

12-hour clock locales like `en-US` would cause the test recording to fail because the resulting date from the test combat log lines would be malformed (`9/27 2:50:54 PM` instead of `9/27 14:50:54`) and cause `videoStartDate` to be null.
Furthermore, `LogLine.date()` assumed the date would only have 5 items which would cause the malformed date to result in an array of:
`[9, 27, 2, 50, '54 PM']` instead of `[9, 27, 2, 50, 54, 'PM]` which would've worked fine since we only care about the first 5 items.
The fix:
- No limit on splitting the date in `LogLine.date()`
- Enforce a locale of `en-GB` on `toLocaleTimeString()` such that we're sure we always get a correct time.
- Output the log lines that we're passing to the combat log parser during a test for easier debugging in the future.

Fix test recording not working for some locales

---

src/main/logutils.ts

`const videoStopDate = ..` in `forceStopRecording()` was shadowing the global variable with the same name that is the one that was supposed to have the value.
Removing `const` fixes this as it no longer declares the variable local to the function.

Fix crash when force stopping a recording

---

src/main/configService.ts
src/main/constants.ts
src/main/logutils.ts

When the content type '2v2' is disabled, the test recording won't run because it runs a test on '2v2'.
This has been fixed by allowing a recording to take place even if we're not allowed to record the test content type, as long as `testRunning` is true.
Refactored `categoryRecordConfigMapping` into
`categoryRecordingSettings`, since we already had a similar object for 'overrun' (`videoOverrunPerCategory`). These have been merged and renamed.
In logutils, the logic regading the allowance of recording content types has been centralised into `allowRecordCategory()`, which also takes `testRunning` into account.
This method is used in `startRecording()` so there's a central place where this is checked and blocked, if needed.
Cleaned up some of the `console.log()` messages and removed the TODO …

Fix unable to test record with 2v2 disabled

---

src/main/constants.ts
src/main/logutils.ts
src/main/types.ts

- Detect any known version of WoW:
- Wow.exe
- WowB.exe
- WowT.exe
- WowClassic.exe
- Any version of WoW will keep the app thinking WoW is running, that is if you start Wow.exe, then start WowClassic.exe, then close Wow.exe it will keep monitoring log files because Classic is still running.

Make detection of WoW running better

---

src/main/keystone.ts

When an unknown dungeon is recorded, it would error out when trying to calculate the keystone upgrade level because the timers can't be found.
This fixes that issue by simply marking the key as depleted.

Fix calculating keystone upgrade level

---

src/main/helpers.ts
src/main/logutils.ts
src/main/types.ts
src/renderer/preload.d.ts
src/settings/preload.d.ts

- Remove unused import `ElectronStore`
- Remove `joinPath()`
- Remove unused import `WoWProcessResultKey`
- Fix missing import of `Metadata`
- Fix `;` => `,` in object key/value
- Fix missing type for `electron.store`

Remove dead code and imports

---

docs/CHANGELOG.md
src/main/configSchema.ts
src/main/main.ts
src/main/obsRecorder.ts
src/main/recorder.ts
src/settings/VideoSettings.tsx
src/settings/useSettings.ts

Replace monitor capture with game capture
- Add Settings for selecting recording mode (Game or Monitor)
- Create `createMonitorCaptureSource()`
- Create `createGameCaptureSource()` to create and configure an input source of `game_capture` with the appropriate settings for capturing any window named 'World of Warcraft'. This will also capture WowClassic.exe, WowB.exe, etc.
- Create `watchVideoSourceSize()` to periodically watch the video source for a change in its dimensions and adjust the scaling factor accordingly to fit the best in the selected output resolution.
Closes #2

Feature: Add Game Capture

---

docs/CHANGELOG.md
src/main/logutils.ts

When a recording is forcibly ended the player combatant isn't properly added to the metadata.

Fix player combatant not saved properly

---

docs/CHANGELOG.md
docs/LocateLogDirectory.md
src/main/combatLogParser.ts
src/main/main.ts
src/renderer/InformationDialog.tsx
src/renderer/RecorderStatus.tsx
src/settings/GeneralSettings.tsx

Add validation for WoW combat log paths such that there will no longer be any confusion about what it is that needs to be selected.
Add a guide in `docs/` that thoroughly explains how to find the appropriate log directory.
Improved styling for the `<InformationDialog/>` component to bring it in line with the rest of the app.
Fixes #211

Feature: Validate WoW log directories

---

docs/CHANGELOG.md
src/main/configSchema.ts
src/main/main.ts
src/main/obsRecorder.ts
src/main/recorder.ts
src/settings/AdvancedSettings.tsx
src/settings/useSettings.ts

Add OBS recording encoder setting
- Add `obsRecEncoder` to config schema and "Advanced Settings"
- Defaults to 'auto', which keeps the old logic of taking the last encoder of the list of available encoders.
- Fix race condition in stop/reconfigure obsRecorder due to not waiting for `obsrecorder.stop()` before calling `obsRecorder.reconfigure()`.
- Add Settings UI elements and helper functions
- Add styling to avoid the dropdown selector having black border/text
Fixes #205

Feature: Configurable OBS encoder

---

src/main/types.ts
src/settings/AdvancedSettings.tsx
src/settings/AudioSettings.tsx
src/settings/ConfigContext.ts
src/settings/ContentSettings.tsx
src/settings/GeneralSettings.tsx
src/settings/Settings.tsx
src/settings/SettingsContext.ts
src/settings/VideoSettings.tsx
src/settings/useSettings.ts

- Give all settings fields a `name` property that matches their state/configuration key since it's included in `event.target.name` which gives us exactly the information we need for the new `modifyConfig()`.
- Add `onChange`, `config` properties to the settings components that provides it with the current configuration as well as a method for changing the config in a central place.
- Remove some extranous whitespace
- Add `FakeChangeEvent` class to mock an event value for when we're saving configuration values delayed from the original change event.
- Remove `ConfigContext`/`SettingsContext`
Adresses parts of #164

Refactor modifyConfig()

---

docs/CHANGELOG.md
src/main/obsRecorder.ts

To avoid Windows not going to sleep because we keep a microphone open, this change introduces a mechanism for only enabling the sound sources when the buffer restarting is canceled, e.g. when a recording is 'started'.
This _can_ result in a few seconds of missing audio in the beginning of the recording, but I _feel_ that's a fair sacrifice.
It works like this:
Start:
- `recorder.start()`
- Cancel buffer restart
- Setup audio sources (`obsRecorder.setupAudioSources()`)
Stop:
- `recorder.stop()`
- `obsRecorder.stop()`
- Clear and release audio sources
Further, simplify the filtering and adding of audio sources.
Fixes #57

Only record audio when recording to buffer

---

docs/CHANGELOG.md
src/activitys/RaidEncounter.ts
src/main/constants.ts
src/settings/AdvancedSettings.tsx

Add difficulty to raid file names

---

docs/CHANGELOG.md
src/main/Recorder.ts
src/main/configSchema.ts
src/main/obsEnums.ts
src/main/types.ts
src/settings/AudioSettings.tsx
src/settings/useSettings.ts

* Add obsForceMono option to configSchema.
* Check obsForceMono in Recorder#addAudioSourcesOBS and sets the appropriate flag on the input device.
* Add switch input to AudioSettings for Force Mono (obsForceMono).
* Slight refactoring of AudioSettings.

282: Play mono microphones through stereo

---

src/main/configSchema.ts
src/settings/AdvancedSettings.tsx

The current iteration allows you to press the down arrow to go into the negatives. Even though you can't save, this should prevent that from happening at all. 
Also changed default to 2 as that's where keystones start.

Bug Fix: Minimum Keystone Settings

---

src/renderer/InformationDialog.tsx

Fixed background-color for dialog popup avoiding style.
Issue #375

Fix styling Dialog popup

---

src/main/constants.ts

Looks like there are some typos in the new DF S3 constants.
[Timer Info](https://www.wowhead.com/guide/mythic-plus-dungeons/dragonflight-season-3/overview)
[DOTI: Murozond's Rise](https://www.wowhead.com/spell=426123/set-keystone-map-dawn-of-the-infinite-murozonds-rise)
[DOTI: Galakrond's Fall](https://www.wowhead.com/spell=426122/set-keystone-map-dawn-of-the-infinite-galakronds-fall)
[Everbloom](https://wago.tools/db2/Map?filter[MapName_lang]=everbloom&page=1)

Fix DF S3 constants

---

src/main/main.ts
src/renderer/VideoPlayer.tsx

Fixes my old issue #457.
This doesn't prevent media keys from working while the window is focused like originally. It should also be noted that the original quirks are still there. For example the keys only work after playback is started once, because they still come from the media session, and aren't actual hotkeys like the letter `k`.
I wasn't able to stop the stop key from working. I don't really understand why, but the "stop" handler just doesn't do anything.

Prevent media keys from working while minimized or not focused

---

src/main/constants.ts

Hi, I noticed that MC / BWL / ZG / Onyxia raids are not recorded.
I checked the logs and noticed that these encounters use unknown difficulty IDs for these 10 / 20 man raids.
I labelled both these entries as 'N' because I didn't notice a convention between the raids tuned for 10 or 20 man.
From my log files I observed the following difficulty IDs:
Molten Core - 226
Blackwing Lair - 186
Zul'Gurub - 226
Onyxia - 186
Please let me know if I can provide any more information to help resolve this. I've attached a recent logfile below that should contain all these raids. The ENCOUNTER_START is detected correctly but the new difficulty ID raises an exception. 
[WarcraftRecorder-2024-10-12.log](https://github.com/user-attachments/files/17447166/WarcraftRecorder-2024-10-12.log)

Added in difficulty IDs for SoD Era for MC / BWL / ZG / Onyxia

---

src/main/Recorder.ts

Disables `allow_transparency` on the Game Capture source. I'm not aware of any uses for this feature when capturing gameplay and it really borks capture when CMAA 2 is enabled in WoW.
If it is needed for something then it should probably be exposed to the user somewhere (but that's outside the scope of this 1-line hack).

Fix CMAA 2 game capture

---

src/main/constants.ts

Added the new difficulty ID (185) for Ruins of AQ
Temple of AQ / Nightmare reuse old difficulty IDs and work correctly.

Added in difficulty IDs for Ruins of AQ SoD P6

---

release/app/package-lock.json
src/main/Recorder.ts
src/main/main.ts
src/main/obsEnums.ts
src/renderer/rendererutils.ts

This PR enables AV1 encoding support using nvidia hardware encoder in series 4000 and later GPUs with custom CRF values (based on personal testing mostly).
On supported cards, benefits include:
- much smaller file size
- up to 8k60 resolution support (including the dreaded 5120x1440)
This also enables hardware rendering in the app. In my testing it works without it, but with high-resolution playback, it's using up to 35% of my CPU (ryzen 7 9800x3d), so I would strongly recommend it.

Enable AV1 nvidia hardware encoding support

---

src/main/main.ts
src/main/menu.ts

Fixes https://github.com/aza547/wow-recorder/issues/668
This PR refactors the menu builder by removing legacy macOS and development-only menu code and streamlining the default menu template. It also adds explicit zoom controls for in-/out/ reset zoom operations. So, menu is not visible, only hotkey access is possible (same as a11y tools).
Removed old Darwin and development context-menu logic from MenuBuilder
Simplified MenuBuilder to always use buildDefaultTemplate
Introduced hidden zoom menu items for zoom in, zoom out, and reset zoom

Refactor menu builder, remove unused code.
